name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 204.10.163.196
          username: kokodev
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/test-deploy
            git pull origin main